### ISSUE TITLE
Typos and Grammar Errors

### ISSUE THREAD

**Issue by OdeclasV** [processing/p5.js-getting-started-es#11]
I recently got the _Introducción a p5.js_ book and have been going thru it in the past few weeks. While doing so, I have encountered a few typos and grammatical errors in Spanish that are easily solvable. 

For instance: in chapter 4, a paragraph part of _Ejemplo 4.-4: aritmética básica_ has the word "predecencia" instead of "precedencia" (see actual text below. I added the emphasis on the word). 

_<p>La expresi&#xF3;n 4 * 5 es evaluada primero porque la multiplicaci&#xF3;n tiene la prioridad m&#xE1;s alta. Luego, se le suma 4 al producto <span class="keep-together">4 * 5</span>, resultando 24. Finalmente, como el <a contenteditable="false" data-primary="assignment operator" data-type="indexterm">&nbsp;</a><em>operador de asignaci&#xF3;n</em> (el signo <em>igual</em>) tiene la menor <b>predecencia</b>, el valor 24 es asignado a la variable <em>x</em>. Esto se puede aclarar con el uso de par&#xE9;ntesis, pero el resultado es el mismo:</p>_

As I continue to go through the book, I can make edits and changes to the markup language and fix the errors I find. I can then open a Pull Request for them to be reviewed, if this would be at all helpful to you. If so, please let me know if you'd like me to proceed, or if there's a better way to go about solving fixing these errors. 

Thanks!

**Comment by montoyamoraga** [comment]
hi @OdeclasV, 
thanks for pointing that out, I will fix that error
You can make pull requests, by changing the files on the folder "content" or by posting them on Issues here, as you wish
Thanks!
